language: php

dist: trusty

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script: composer install

script: phpunit

matrix:
  include: # https://github.com/travis-ci/travis-ci/issues/7712#issuecomment-300553336
    - php: "5.3"
      dist: precise
